version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/Moment/

hooks:
    BeforeInstall:
        - location: scripts/beforeInstall.sh
          runas: ubuntu
          timeout: 300
    ApplicationStop:
        - location: scripts/stop.sh
          runas: ubuntu
          timeout: 300
    AfterInstall:
        - location: scripts/initialize.sh
          runas: ubuntu
          timeout: 300
    ApplicationStart:
        - location: scripts/start.sh
          runas: ubuntu
          timeout: 300
